# 1ª PARTE

## Ejercicio 1

### Función resumen básico estadístico de un array unidimesional.

In [81]:
import numpy as np

In [87]:

def resum_estad(x):
    if x.ndim < 2:
        media_arit=np.mean(x).round(2)
        mediana=np.median(x).round(2)
        varianza=np.var(x).round(2)
        desviacion_tipica=np.std(x).round(2)
    else:
        print("¡Error!")
    print('La media es:', media_arit), print('La mediana es:', mediana), print('La varianza es:', varianza),  print('La desviación típica es:', desviacion_tipica)


array_uni= np.arange(50, 101)

resum_estad(array_uni)


La media es: 75.0
La mediana es: 75.0
La varianza es: 216.67
La desviación típica es: 14.72


## Ejercicio 2

### Función que crea un cuadrado NxN de números aleatorios entre 0 y 100

In [88]:
from numpy import random

In [89]:

def cuadrado_NxN():
    j=int(input("Ingrese número de filas que desee: "))
    k=int(input("Ingrese número de columnas que desee: "))
    cuadrado= random.randint (0,101, size=(j, k))
    return cuadrado

NxN=cuadrado_NxN()

print(NxN)

Ingrese número de filas que desee: 4
Ingrese número de columnas que desee: 8
[[54  8 42 32 36  2 93 33]
 [10 54 94 91 33 62 16 66]
 [66 21 54  5 57  7  0 14]
 [87 19 39 84 28 59 19 96]]


## Ejercicio 3

### Función que calcula la suma total por fila y por columna

In [90]:

def suma_filas_columnas(x):
    suma_filas=np.sum(x, axis=1)
    suma_columnas=np.sum(x, axis=0)
    print('La suma de cada fila es:', suma_filas)
    print('La suma de cada columna es:', suma_columnas)


array_ejempl=random.randint (0,101, size=(6, 10))
print('Suma de filas y columnas del suguiente array:', '\n', array_ejempl)
print('\n'*3)
suma_filas_columnas(array_ejempl)


Suma de filas y columnas del suguiente array: 
 [[40 40 39 88 93 45 37 85 50  1]
 [16 56 30 19  4 65 47 56 96 52]
 [23 66 80 34 59 10 38 23 52 43]
 [ 4 22 54 24 61 50 25 18 78 12]
 [ 5  5 48 56 66 15 86 33 26 35]
 [21 23 50 69  7 28 85 72 13 46]]




La suma de cada fila es: [518 441 428 348 375 414]
La suma de cada columna es: [109 212 301 290 290 213 318 287 315 189]


## Ejercicio 4

### Función por pasos para el cálculo del coeficiente de correlación

In [91]:

def coeficiente_correlacion_manual(x, y):
    suma_x=np.sum(x)
    suma_y=np.sum(y)

    prod_escal=np.dot(x,y)

    sum_x2=np.sum(x**2)
    sum_y2=np.sum(y**2)
    
    #longitud por vector
    long_x=len(x)
    long_y=len(y)
    
    # Medias aritméticas
    media_x=suma_x/long_x
    media_y=suma_y/long_y
    
    # Covarianza
    cova=prod_escal/long_x - media_x*media_y
    # o "/long_y"
    
    # desviaciones típicas
    desvT_x=np.sqrt(sum_x2/long_x - np.sum(media_x**2))
    desvT_y=np.sqrt(sum_y2/long_y - np.sum(media_y**2))
    
    # Finalmente Coeficiente de correlación
    coef_correl=cova/(desvT_x*desvT_y)
    
    return coef_correl


## Ejemplo para aplicación de la función para ingresos y edad
x=np.array([1900, 800, 1300, 1500, 2750, 1100, 1500, 2000, 1700, 2300, 3100 ])
y=np.array([31, 18, 22, 28, 35, 27, 20, 29, 40, 38, 45])

coeficiente_correlacion_manual(x, y).round(5)

0.81934

### Coeficiente de correlación con función de Numpy


In [92]:
coeficiente_correlacion_funcion=(np.corrcoef(x, y).round(5))
coeficiente_correlacion_funcion

array([[1.     , 0.81934],
       [0.81934, 1.     ]])

#### Los resultados del coeficiente de correlación "manual" y con la función de Numpy son coincidentes.